---
title: "Object Detector"
autor: "Marija Stanojcic"
output: html_notebook
---

```{r}
# Load libraries
library(jpeg)
library(httr)
library(tidyverse)
library(magick)
library(ggplot2)
library(grDevices)
```


```{r}
# Visualize the image
jj <- readJPEG("dog-human.jpg",native=TRUE) 

plotly(
plot(0:1,0:1,type="n",ann=TRUE,axes=TRUE, asp = 1) +
rasterImage(jj,0,0,1,1)
)
```



```{r}
model_endpoint_object_detector <- paste0('http://max-object-detector.max.us-south.containers.appdomain.cloud/', 'model/predict?threshold=0.7')

response_object <- httr::POST(model_endpoint_object_detector,
                       body = list(image = upload_file("baby-bear.jpeg"), type = "image/jpeg"), encode = c("multipart")
) %>% content()
```

```{r}
response_object
```


```{r}
# not working
# do.call(what = rbind.data.frame, args = response_object$predictions)
```

```{r}
my_data <- data.frame()
det_box <- data.frame()
row <- character()
det_box_row <- vector()

for (i in 1:length(response_object$predictions)){
  row <- cbind(response_object$predictions[[i]]$label_id, response_object$predictions[[i]]$label, response_object$predictions[[i]]$probability)
  my_data <- rbind(row, my_data) # predictions
  det_box_row <- rbind(t(matrix(unlist(response_object$predictions[[i]]$detection_box), nrow=4)))
  det_box <- rbind(det_box_row, det_box) # coordinates 
}

colnames(my_data) <- c("LabelID", "Label", "Probability")
my_data %>% arrange(desc(Probability)) -> my_data

my_data
```

```{r}
n <- nrow(my_data)
paste0(n, " objects indentified.")
```

```{r}
for ( i in 1:n){
  cat(paste0("The object ", i, " is ", my_data$Label[i],".", "\n"))

}
```

Getting the cordinates for the boxes.

```{r}
colnames(det_box) <- c("ymin", "xmin", "ymax", "xmax")
det_box
```
```{r}
response_object$predictions[[4]]$detection_box
```


```{r}
response_object$predictions
```

```{r}
plot(0:1,0:1,type="n",ann=FALSE,axes=FALSE, asp = 1)
rasterImage(jj,0,0,1,1)
rect(det_box$xmin[1], det_box$ymin[1], det_box$xmax[1], det_box$ymax[1], border = "green", lty = "solid", lwd = 3)
rect(det_box$xmin[2], det_box$ymin[2], det_box$xmax[2], det_box$ymax[2], border = "green", lty = "solid", lwd = 3)
```

```{r}
slika <- image_read("baby-bear.jpeg")
#slika <- image_flip(slika)

plot(0:1,0:1,type="n",asp = 1,axes=TRUE, xlim = c(0,1), ylim= c(0,1)) +
rasterImage(slika,0,0,1,1) +
rect(det_box$xmin[1], 1- det_box$ymax[1], det_box$xmax[1], 1- det_box$ymin[1], border = "green", lty = "solid", lwd = 3) +
rect(det_box$xmin[2], 1- det_box$ymax[2], det_box$xmax[2], 1- det_box$ymin[2], border = "green", lty = "solid", lwd = 3)

```

```{r}
info <- image_info(slika)
```

```{r}
image_flip(slika)
```


```{r}
grDevices::jpeg("moja_slika_new.jpeg", width = info$width, height = info$height) +
plot(0:1,0:1,type="n",ann=FALSE,axes=FALSE) + 
  rasterImage(slika,0,0,1,1) +
  for (i in 1:n) {
    rect(det_box$xmin[i], 1-det_box$ymax[i], det_box$xmax[i], 1- det_box$ymin[i], border = "green", lty = "solid", lwd = 3)} 


#dev.off()
```

```{r}
moja_slika2 <- image_read("moja_slika.jpeg")
image_info(moja_slika2)
```

```{r}
#paste0(width(slika))
#height(slika)
```


```{r}
print(moja_slika2)
```


```{r}
geom = paste0(width(jj), "x", height(jj))
image_resize(moja_slika2, "640x962")
```

```{r}
image_trim(moja_slika2)
```
```{r}
image_strip(moja_slika2)
```

```{r}
library(grid)
slika
g <- rasterGrob(slika)

qplot(0:1, 0:1, geom = "blank") +
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  theme_void()
```




```{r}
swiss.pca$rotation
```


```{r}
library(plotrix)

 x<-rnorm(10)
 y<-rnorm(10)
 plot(x,y,type="p")
 nums<-c("one","two","three","four","five","six","seven","eight","nine","ten")
 boxed.labels(x,y-0.1,nums)
 # now label a barplot
 xpos<-barp(c(1,3,2,4))
 boxed.labels(xpos$x,0.5,nums[1:4])
 # and add labels below the x axis ticks
 boxed.labels(xpos$x,-0.4,c("First","Second","Third","Fourth"))
 # perform a PCA on the "swiss" dataset and plot the first two components
 data(swiss)
 swiss.pca<-prcomp(swiss)
 plot(swiss.pca$rotation[,1:2],xlim=c(-1,0.2),main="PCA of swiss dataset",
  type="n")
 boxed.labels(swiss.pca$rotation[1:6],swiss.pca$rotation[7:12],ypad=1.5,
  colnames(swiss),  col="black")
```




```{r}
#library(plotrix)

 x<-rnorm(20)
 y<-rnorm(20)
 xlim<-range(x)
 xspace<-(xlim[2]-xlim[1])/20
 xlim<-c(xlim[1]-xspace,xlim[2]+xspace)
 ylim<-range(y)
 yspace<-(ylim[2]-ylim[1])/20
 ylim<-c(ylim[1]-yspace,ylim[2]+yspace)
 plotlabels<-
  c("one","two","three","four","five","six","seven","eight","nine","ten",
  "eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen",
  "eighteen","nineteen","twenty")
 plot(x=x,y=y,xlim=xlim,ylim=ylim,main="Test thigmophobe.labels")
 # skip the almost invisible yellow label, make them bold
 thigmophobe.labels(x,y,plotlabels,col=c(2:6,8:12),font=2)
```






















